[font]
size = 14.0

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"
