theme = "kanagawa"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
[keys.normal.space]
"C-d" = ":yank-diagnostic"
[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.insert]
C-space = "completion"
